## this file i just pushed to git to show the code only, of course in reality this files NEVER GET PUSHED and either local only files or come from Vaults like HashiCorp etc...
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  PORT: "4001"
  # this basically should Should point at the real PG service (or managed DB host as common systems do) in-cluster, not localhost.
  DB_HOST: postgres-svc
  DB_PORT: "5432"
  DB_USERNAME: mohamed
  DB_PASSWORD: "changeme-local-only"
  DB_NAME: derq_db
  DB_SYNC: "false"
  CORS_ORIGIN: https://derq.com
