apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-debug
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - name: frontend-svc
          port: 3000